services:
  db:
    image: postgres
    env_file: ./env/db.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - db-data-volume:/var/lib/postgresql/

  keycloak:
    build: ./backend/keycloak-26.4.6/
    env_file: ./env/keycloak.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  wildfly:
    build: ./backend/lab4/
    ports:
      - "12030:12030"
      - "9990:9990"
    env_file: ./env/wildfly.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend/
    env_file: ./env/frontend.env
    ports:
      - "4200:4200"

volumes:
  db-data-volume: